fix: entity motion inconsistencies
SwitchCraftCC/Plethora-Fabric pull request #55
Opened 2023-05-08 00:30 UTC by hugeblank

Fixes SwitchCraftCC/Plethora-Fabric#52. 

Adds a pair of mixins that calculate velocity from the entity's current position and the position in the tick prior.

Test program: 
```lua
local mods = peripheral.wrap("back")
mods.canvas().clear()
local text = mods.canvas().addText({0,0}, "")
while true do
    local meta = mods.getMetaOwner()
    text.setText(meta.motionX.." "..meta.motionZ)
end
```
Use on NI with introspection module, overlay glasses, and entity sensor. 
Move around, see velocity change.

2023-05-08 08:34 UTC, hugeblank commented
When changing dimensions, for a single tick, the entity velocity spikes. Should this be intended behavior? 
Some alternatives:
1. Providing the dimension the entity is in in the metadata so the player can account for this programmatically.
2. Storing positions per dimension. This has the side effect that when entering the nether, heading to another portal and exiting the nether through it, the overworld velocity will spike. 
3. Assuming the entity's velocity is always 0 when entering any dimension. I think this might be the best bet, but I like the idea of exposing the dimension the entity is in too...

2023-05-08 12:36 UTC, Lemmmy requested changes

2023-05-08 12:36 UTC, Lemmmy commented on src/main/java/io/sc3/plethora/mixin/EntityMixin.java
> +    public Vec3d motion = Vec3d.ZERO;
Don't forget @Unique here too
```suggestion
    @Unique
    private Vec3d motion = Vec3d.ZERO;
```

2023-05-08 12:36 UTC, Lemmmy commented on src/main/java/io/sc3/plethora/mixin/EntityMixin.java
> +    public Vec3d prevPos = Vec3d.ZERO;
```suggestion
    private Vec3d prevPos = Vec3d.ZERO;
```

2023-05-08 12:36 UTC, Lemmmy commented on src/main/java/io/sc3/plethora/mixin/EntityMixin.java
> +    }
I don't think the velocity spiking is necessarily bad behavior, but you could store and compare the world here, setting the velocity back to 0 if the dimension is different to the previous tick. Something like this might work:

```suggestion
    private RegistryKey<World> prevWorld;

    @Override
    public void storePrevPos() {
        var entity = (Entity) (Object) this;
        var pos = entity.getPos();
        var world = entity.getWorld().getRegistryKey();
        
        // Avoid velocity spikes when changing dimensions
        if (prevWorld != world) {
            prevWorld = world;
            motion = Vec3d.ZERO;
        } else {
            motion = pos.subtract(prevPos);        
        }
        
        prevPos = pos;
    }
```

Double check this still works with tickPassenger. I believe it will; the prevPos gets observed twice but the world has already changed by the time tickPassenger is called.

2023-05-08 20:53 UTC, hugeblank commented on src/main/java/io/sc3/plethora/mixin/EntityMixin.java
> +    }
Actually, entities that have a passenger suppress the dimension change for both itself and the passenger. The one exception to this that I can think of is parrots, but they:
a) aren't a passenger in the same way that mountable entities are
b) don't get detected by the sensor anyways.

e20bcd3 adds the world-change velocity reset though, it has been tested and works perfectly.

2023-05-10 18:20 UTC, Lemmmy approved these changes

2023-05-10 18:20 UTC, Lemmmy commented
LGTM, Huge thanks for this!

2023-05-10 18:20 UTC, merged